site_name: BCIT Sailbot

site_url: http://bcit-sailbot.ca
repo_url: https://github.com/matt1795/BCiT-Sailbot

pages:
- Home: 'index.md'
- About Us:
    - The Team: 'about/team.md'
    - Sponsorship: 'about/sponsorship.md'
    - Contact Us: 'about/contact.md'
- Design Documentation:
    - Control System: 'design/control.md'
- Team Documents:
    - Project Guidelines: 'team/guidelines.md'
    - Using Zenhub: 'team/zenhub.md'
    - Coding Standard: 'team/standard.md'
    - Testing: 'team/testing.md'

markdown_extensions:
    - Markdown-Latex
