site_name: BCIT Sailbot

site_url: http://bcit-sailbot.ca
repo_url: https://github.com/matt1795/BCiT-Sailbot

pages:
- Home: 'index.md'
- About Us:
    - The Team: 'about/team.md'
    - Sponsorship: 'about/sponsorship.md'
    - Budget: 'about/budget.md'
    - Current Progress: 'about/progress.md'
    - Contact Us: 'about/contact.md'
- Design Documentation:
    - Project Overview: 'design/overview.md'
    - Command Set: 'design/commandSet.md'
    - Wing Sail Design and Manufacturing: 'design/wingSailReport.md'
- Team Documents:
    - Project Guidelines: 'team/guidelines.md'
    - Using Zenhub: 'team/zenhub.md'
    - Coding Standard: 'team/standard.md'
    - Testing: 'team/testing.md'
